package Candidatures;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import Entities.Employe;
import Interfaces.UserintRemote;
import javafx.event.ActionEvent;

public class AuthController {
	@FXML
	private Button profBut;
	@FXML
	private TextField login;
	@FXML
	private TextField name;
	// Event Listener on Button[#profBut].onAction
	@FXML
	public void afficherDetail(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		
		String jndiName="ElikiaSer-ear/ElikiaSer-ejb/UserImp!Interfaces.UserintRemote"; 
	 	Context context = new InitialContext();
	 	UserintRemote proxy=(UserintRemote) context.lookup(jndiName);
		
		int util=Integer.parseInt(login.getText());
		Employe emp=proxy.getEmploye(util);
		if(name.getText().equals(emp.getNom())){
		//int ent=emp.getEntreprise().getId();
		Node source = (Node) event.getSource();
        Stage stage = (Stage) source.getScene().getWindow();
        stage.close();
        
        Stage primaryStage= new Stage();
        FXMLLoader FL = new FXMLLoader(getClass().getResource("DisplayCFXML.fxml"));
        Parent root = FL.load();
        Scene scene = new Scene(root);
        primaryStage.setTitle("Acceuil");
        primaryStage.setScene(scene);
        primaryStage.show();
		}
		else{
			System.out.println("no");
		}
	}
}
